### PR TITLE
L ui taglibs pulls 2

### PR DESCRIPTION
**Pull request by mwilliams2014**
Hey @westonhancock,

I had to do a hard reset and so I lost your latest changes for search-paginator, search-toggle, rss, and rss-settings tags. Can you add your changes for those tags only to the tld and send me a new pull request with your changes.

### CODE REVIEW

**Comment by westonhancock** [comment]
yeah. I'll do that as soon as I have a chance.

Weston Hancock
Junior Software Engineer, UI Engineering
Liferay, Inc. Liferay.com <http://www.liferay.com>
Enterprise. Open Source. For Life.

**Comment by mwilliams2014** [comment]
Thanks

**Comment by westonhancock** [comment]
what about search-iterator?

Weston Hancock
Junior Software Engineer, UI Engineering
Liferay, Inc. Liferay.com <http://www.liferay.com>
Enterprise. Open Source. For Life.

**Comment by mwilliams2014** [comment]
Sorry, yeah that one as well. All of your work is in there, just your commits were lost for those tags. I'm going to remove your work from those tags, and re-push my changes to this pull request. Then you can add your changes back in.

**Comment by mwilliams2014** [comment]
@westonhancock Everything should be good to go now. If you'll just add those tags back in to the tld and send me a pull request, I'll add my changes on top.

**Comment by westonhancock** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
